# -*- coding: utf-8 -*-
"""CHE447sklearnWithHeatTransferPlotAdded.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgLReP4ebpg0s17F7uDCfqwn6QhQujuo
"""

from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.model_selection import LeaveOneOut, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

EXCEL_PATH = Path("/content/drive/MyDrive/CHE44727_dataset_reframed.xlsx")
SHEET_NAME = "Sklearn_Ready"

FEATURE_COLS = [
    "Tinf_K",
    "h_conv_W_m2K",
    "rho_ice_kg_m3",
    "Cp_ice_J_kgK",
    "dH_melt_eff_J_kg",
]

TARGET_COLS = [
    "t_melt_onset_s",
    "t_noticeable_melt_s",
    "t_noticeable_soggy_s",
    "t_unacceptably_soggy_s",
    "t_finish_s",
]

import os

print(EXCEL_PATH)
print(EXCEL_PATH.exists())
!ls -l /content/drive/MyDrive | head
!file /content/drive/MyDrive/CHE44727_dataset_reframed.xlsx

df = pd.read_excel(EXCEL_PATH, sheet_name=SHEET_NAME, header=2)

needed_cols = FEATURE_COLS + TARGET_COLS
print(df.columns.tolist())

df_model = df.dropna(subset=needed_cols).copy()

X = df_model[FEATURE_COLS]
y = df_model[TARGET_COLS]

model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("rf", RandomForestRegressor(
        n_estimators=300,
        max_depth=4,
        random_state=42
    ))
])

loo = LeaveOneOut()
y_pred = cross_val_predict(model, X, y, cv=loo)
pred_df = pd.DataFrame(y_pred, columns=[f"pred_{c}" for c in TARGET_COLS], index=df_model.index)

h = df_model["h_conv_W_m2K"].values
actual = df_model["t_melt_onset_s"].values
predicted = pred_df["pred_t_melt_onset_s"].values

m_act,  b_act  = np.polyfit(actual,    h, 1)
m_pred, b_pred = np.polyfit(predicted, h, 1)

x_line = np.linspace(min(actual.min(), predicted.min()),
                     max(actual.max(), predicted.max()), 200)

plt.figure(figsize=(6, 5))

# Scatterplot of predicted and actual data points
plt.scatter(actual,h,label="COMSOL", color="coral",edgecolors="k",linewidths=0.5,alpha=0.8)
plt.scatter(predicted,h,label="sklearn", color="steelblue",edgecolors="k",linewidths=0.5, alpha=0.8)

# Regression lines
plt.plot(x_line,m_act*x_line+b_act,color="coral",linewidth=1.5,linestyle="--",label="COMSOL fit")
plt.plot(x_line,m_pred*x_line+b_pred,color="steelblue",linewidth=1.5,linestyle="--",label="sklearn fit")

# Equation labels
eq_actual = f"COMSOL: y = {m_act:.6f}x + {abs(b_act):.3f}"
eq_pred   = f"sklearn: y = {m_pred:.6f}x + {abs(b_pred):.3f}"

plt.text(
    0.30, 0.97,
    f"{eq_actual}\n{eq_pred}",
    transform=plt.gca().transAxes,
    fontsize=9,
    verticalalignment="top",
    bbox=dict(boxstyle="round", facecolor="white", alpha=0.7)
)

plt.xlabel("Melt Onset Time (s)")
plt.ylabel("Heat Transfer Coefficient (W/m²K)")
plt.title("Melt Onset Time vs Heat Transfer Coefficient")
plt.legend()
plt.tight_layout()
plt.show()

for i, target in enumerate(TARGET_COLS):
    actual = y.iloc[:, i].values
    pred = y_pred[:, i]

    plt.figure(figsize=(5, 3))
    plt.scatter(actual, pred)
    lo = min(actual.min(), pred.min())
    hi = max(actual.max(), pred.max())
    plt.plot([lo, hi], [lo, hi], linestyle="--")
    plt.xlabel(f"Actual {target}")
    plt.ylabel(f"Predicted {target}")
    plt.title(target)
    plt.tight_layout()
    plt.show()

model.fit(X, y)

rf = model.named_steps["rf"]
importance_df = pd.DataFrame({
    "feature": FEATURE_COLS,
    "importance": rf.feature_importances_,
}).sort_values("importance", ascending=False)

plt.figure(figsize=(7, 5))
plt.bar(importance_df["feature"], importance_df["importance"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("Importance")
plt.title("Relative Parameter Importance")
plt.tight_layout()
plt.show()