# -*- coding: utf-8 -*-
"""Group5CHE447PowerFitToIceCreamData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTAbGzLnuEEsZYH6ThGZkSWQCks5XJKe
"""

#Import libraries
import numpy as np
import matplotlib.pyplot as plt

# Experimental Data from Additional Trials in COMSOL
# Parameters used for Tillamook Vanilla Bean at 21C
t = np.array([3399.85,2132.15,1402.05,961.9856,840.34,683.747,594.4157])
h = np.array([3,5,8,10,12,16,20])

# Power law: h = a * t^b
coeffs = np.polyfit(np.log(t), np.log(h), 1)
b = coeffs[0]
a = np.exp(coeffs[1])
print(f"h = {a:.4f} * t^({b:.4f})")

t_fit = np.linspace(t.min(), t.max(), 200)
h_fit = a * t_fit**b

plt.figure(figsize=(8, 5))
plt.scatter(t, h, color='red', label='COMSOL Data', zorder=5)
plt.plot(t_fit, h_fit, color='orange', label=f'h = {a:.2f} · t^({b:.4f})')
plt.xlabel('Time to Noticeable Sogginess (s)')
plt.ylabel('Heat Transfer Coefficient (W/m²K)')
plt.title('Power Law Fit of Time to Noticeable Sogginess')
plt.legend()
plt.grid(True)
plt.show()